### ISSUE TITLE
Move to next dependencies version

### ISSUE THREAD

**Issue by baedorf** [tailoringexpert/platform#206]

**Comment by vishalsingh2972** [comment]
@baedorf I would like to work on this if it is still open, also any specific dependency that you want to target or should I update all the dependencies?

**Comment by baedorf** [comment]
Ticket is already implemented, only ticket not closed yet.

Background:
This application is implemented as a multi-tenant platform. Each tenant that wants to be deployed on the platform must have valid dependencies. These dependencies are defined in an external BOM: tailoringexpert-dependencies. For each new version of the platform, a new version of tailoringexpert-dependencies is started in advance.
To use this new BOM, an issue is created to be used in a new gitflow feature.
